name: Load Test

on:
  workflow_dispatch:
    inputs:
      threadgroup:
        description: 'Number of users'
        required: true
        default: 0
        type: number
      rampup:
        description: 'User rampup'
        required: true
        default: 0
        type: number

jobs:
  pttest:
    name: ${{ github.run_number }} - Load Testing with ${{ github.event.inputs.threadgroup }} users and ramp up of ${{ github.event.inputs.rampup }} seconds
    runs-on: [self-hosted, linux, java]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3

      - name: Install dependencies
        run: pip install --upgrade pip matplotlib pandas openpyxl

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Load Testing
        uses: azure/load-testing@v1
        with:
          loadTestConfigfile: './Configuration/Loadtest.yml'
          loadTestResource: ${{ github.event.inputs.threadgroup }}
        env:
          THREADGROUP: ${{ github.event.inputs.threadgroup }}
          RAMPUP: ${{ github.event.inputs.rampup }}
